export { default as tell } from './src/tell';
export { default as greeter } from './src/greeter';
export { default as joinMessage } from './src/joinMessage';
export { default as noU } from './src/noU';
export { default as flipCoin } from './src/flipCoin';
export { default as rollDice } from './src/rollDice';
export { default as trolls } from './src/trolls';
export { default as rockPaperScissors } from './src/rockPaperScissors';
export { default as docs } from './src/docs';
